👷 testing something

diff --git a/.github/workflows/vitest.yml b/.github/workflows/vitest.yml
--- a/.github/workflows/vitest.yml
+++ b/.github/workflows/vitest.yml
@@ -28,6 +28,6 @@ jobs:
     - name: Run tests
       run: pnpm exec vitest run -- --echo
 
-    - name: Check exit code
-      if: ${{ failure() }}
-      run: exit 1
+    # - name: Check exit code
+    #   if: ${{ failure() }}
+    #   run: exit 1
